#! /bin/sh
#  ____ _____
# |  _ \_   _|  Derek Taylor (DistroTube)
# | | | || |    http://www.youtube.com/c/DistroTube
# | |_| || |    http://www.gitlab.com/dwt1/
# |____/ |_|
#
# A customized bspwmrc for the bspwm window manager.
# https://github.com/baskerville/sxhkd
# https://github.com/baskerville/bspwm

#### AUTOSTART ####
sxhkd &
picom -b &
xsetroot -cursor_name left_ptr &
nitrogen --restore &
./.config/bspwm/dual_monitor.sh
./.config/polybar/launch.sh &
flameshot &

#### MONITORS ####
if xrandr --query | grep 'DisplayPort-2 connected'; then
    bspc monitor HDMI-A-0 -d 1 4 6
    bspc monitor DisplayPort-2 -d 2 3 5
else
    bspc monitor HDMI-A-0 -d 1 2 3 4 5 6
fi

if grep -q PATTERN file.txt; then
    echo found
else
    echo not found
fi

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   0
bspc config bottom_padding                40
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_follows_monitor      true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-secondary-monitor_DisplayPort-2)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main-monitor_HDMI-A-0)

bspc rule -a Emacs           desktop='1' state=tiled follow=on
bspc rule -a Google-chrome   desktop='2' state=tiled
bspc rule -a Slack           desktop='3' state=tiled
bspc rule -a Spotify         desktop='4' state=tiled follow=on
bspc rule -a TelegramDesktop desktop='6' state=tiled
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
